### ISSUE TITLE
[Go] Problem with Azure auth provider

### ISSUE THREAD

**Issue by lynxnot** [ahmetb/kubectx#232]
The new go implementation of `kubens` seems to have a problem with Azure authentication:

```
$ ./kubens 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10f4d20]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc0002fbac0, 0xc0001dec60, 0xd, 0xc0001dec60)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:276 +0x390
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc0002fbac0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:194 +0x453
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc0003dcfe0, 0xc0002ae600, 0x13c0213, 0xa, 0xc00040c360)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:125 +0x81
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0003dd000, 0xc0002ae500, 0xc0003dd000, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c0
net/http.send(0xc0002ae500, 0x15643a0, 0xc0003dd000, 0x0, 0x0, 0x0, 0xc000182c18, 0x203000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:252 +0x43e
net/http.(*Client).send(0xc0003cbf80, 0xc0002ae500, 0x0, 0x0, 0x0, 0xc000182c18, 0x0, 0x1, 0xc00040c000)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:176 +0xfa
net/http.(*Client).do(0xc0003cbf80, 0xc0002ae500, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:699 +0x44a
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc00033e960, 0xc00037b830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3e9
k8s.io/client-go/rest.(*Request).Do(0xc00033e960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xd8
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc0003d5850, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x177
main.queryNamespaces(0xc0001d1e68, 0xc000354080, 0xe, 0xc000354030, 0x8, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:73 +0x2b0
main.ListOp.Run(0x15647c0, 0xc000182008, 0x15647c0, 0xc000182010, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:37 +0x202
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:20 +0x108
```

**Comment by ahmetb** [comment]
Sounds like the problem is with Azure auth driver. We don’t do anything Azure-specific. I recommend debugging.

**Comment by ahmetb** [comment]
Also when you get this error, does kubectl continue to work fine?

**Comment by lynxnot** [comment]
> Also when you get this error, does kubectl continue to work fine?

Yes kubectl works fine. Im not a go dev, i'll ping our cloud team to see if someone can debug further.
