### ISSUE TITLE
[windows] Kubens doesn't work while kubectx works in binary version 9.0

### ISSUE THREAD

**Issue by eshepelyuk** [ahmetb/kubectx#233]
I'm windows user and using msys2 as a linux like env, using its bash as my shell.
Also I'm using kubectl installed by chocolatey.

I've been using kubectx and kubens in bashform for about a year - without any problems.
So I've tried to download a new inary version recently and try it.

So, `kubectx` just works - no issue so far, but surprisedly `kubens` fails with following error 

```
/d/projects
$ kubens
error: could not list namespaces (is the cluster accessible?): failed to initialize config: invalid configuration: unable to read certificate-authority testcluster.nas.local.crt for testcluster.nas.local due to open testcluster.nas.local.crt: The system cannot find the file specified.

/d/projects
$ kubectx
hrzn-dev-stage-k8s.nas.local
hrzn-prod-k8s.hrzn.prod
minikube
testcluster.nas.local
```
@ahmetb - please let me know how can I help to debug the issue, what are the missing details.

Environment:
* windows 10
* kubectl version
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by SergeyIBM47** [comment]
I have the same problem, could someone help to make it works?

**Comment by ahmetb** [comment]
First of all it’s definitely funny that suddenly within 10 minutes two msys2 users show up :)

If one of you can run with DEBUG=1 set as env var, I think we can get some more out of it. 

From the error, I am suspecting this is because there are some CA cert paths in kubeconfig path that are not working. This sounds similar to #229.

**Comment by eshepelyuk** [comment]
> First of all it’s definitely funny that suddenly within 10 minutes two msys2 users show up :)

we're colleagues

**Comment by ahmetb** [comment]
> we're colleagues

I highly recommend not doing this in open source repositories.
This falsely makes maintainers think you’re two independent parties ran into this issue, which may indicate it's a widespread problem (although msys user base is probably small). So it's better not to exhibit this form of +1'ing in open source.

I’m suspecting this is indeed #229. When you go to the directory that contains the `testcluster.nas.local.crt` and run `kubens`, does it work? If so, that's the same issue.

**Comment by eshepelyuk** [comment]
@ahmetb check the output, the issue is the same

```
~/.kube
$ env DEBUG=1 kubens
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1134651]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*oidcAuthProvider).idToken(0xc000372300, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/oidc/oidc.go:281 +0x701
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*roundTripper).RoundTrip(0xc00037be40, 0xc00022c400, 0x13e131d, 0xa, 0xc0003ad280)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/oidc/oidc.go:199 +0x83
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc00037be60, 0xc00022c300, 0xc00037be60, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c7
net/http.send(0xc00022c300, 0x1584520, 0xc00037be60, 0x0, 0x0, 0x0, 0xc000006e38, 0x2030000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc000372cc0, 0xc00022c300, 0x0, 0x0, 0x0, 0xc000006e38, 0x0, 0x1, 0xc0003acf20)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc000372cc0, 0xc00022c300, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc0002bac30, 0xc000121830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3f0
k8s.io/client-go/rest.(*Request).Do(0xc0002bac30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc000383290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x17e
main.queryNamespaces(0xc000121e68, 0xc00020ba20, 0x15, 0xc00020b900, 0x12, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:73 +0x2b7
main.ListOp.Run(0x1584900, 0xc000006018, 0x1584900, 0xc000006020, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:37 +0x209
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:20 +0x10f

~/.kube
$ ls -la `pwd` | grep test
-rw-r--r-- 1 eshepelyuk eshepelyuk 1042 Жов 31  2019 testcluster.k8s.local.crt
-rw-r--r-- 1 eshepelyuk eshepelyuk 1042 Гру  3 20:27 testcluster.nas.local.crt
```

**Comment by eshepelyuk** [comment]
@ahmetb yes - you're right. Closing this in favour of #229
