### ISSUE TITLE
AKS get all namespace is error ` runtime error: invalid memory address or nil pointer dereference` with azure-cli.

### ISSUE THREAD

**Issue by dvgamerr** [ahmetb/kubectx#289]
**AKS**

```bash
λ kubectx
**cg-aks-service-prd**
ppe-develop
ppe-prod
```

and use kubens
```bash
λ kubens
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1115be7]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc00027bc40, 0xc000160bb0, 0xd, 0xc000160bb0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:276 +0x397
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc00027bc40, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:194 +0x45a
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc0003bbb60, 0xc000230800, 0x13e1398, 0xa, 0xc0003ea4c0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:125 +0x88
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0003bbb80, 0xc000230700, 0xc0003bbb80, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c7
net/http.send(0xc000230700, 0x1584660, 0xc0003bbb80, 0x0, 0x0, 0x0, 0xc000006c88, 0x2030000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc0003aff80, 0xc000230700, 0x0, 0x0, 0x0, 0xc000006c88, 0x0, 0x1, 0xc0003ea160)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc0003aff80, 0xc000230700, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc0002c0b40, 0xc000129830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3f0
k8s.io/client-go/rest.(*Request).Do(0xc0002c0b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc0003d87a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x17e
main.queryNamespaces(0xc000129e68, 0xc0002f9180, 0x12, 0xc0003160b9, 0x3, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:64 +0x24a
main.ListOp.Run(0x1583fe0, 0xc000074140, 0x1583fe0, 0xc000074190, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:36 +0x209
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:21 +0x116
```
but use `kubectl get ns -A` works.
```
λ kubectl get ns -A
NAME                   STATUS   AGE
daas                   Active   33d
default                Active   51d
fms                    Active   34d
kafka                  Active   33d
kube-node-lease        Active   51d
kube-public            Active   51d
kube-system            Active   51d
kubecost               Active   22d
kubernetes-dashboard   Active   35d
monitoring             Active   26d
pmp                    Active   14d
slkadmin               Active   27d
tms                    Active   41d
```

**Comment by robindv** [comment]
I had the same error but updating to v0.9.3 worked for me.
